templateDir: codegen-config/python-fastapi-models/templates
additionalProperties:
  infoEmail: "info@lightspark.com"
  packageUrl: https://github.com/uma-universal-money-address/umaaas-api
  packageVersion: 0.0.5
packageName: umaaas_api
files:
  setup_cfg.mustache:
    destinationFilename: setup.cfg
  README.mustache:
    destinationFilename: README.md
  Pipfile.mustache:
    destinationFilename: Pipfile
  LICENSE: {}
  pyproject.toml: {}
  .pylintrc: {}
  .pyre_configuration: {}
  MANIFEST.in: {}
  setup.py: {}
  openapi.mustache:
    destinationFilename: src/umaaas_api/openapi.yaml
  py.typed:
    folder: src
