apis:
  umaas@v1:
    root: ./openapi.yaml

extends:
  - recommended

rules:
  operation-description: error
  operation-operationId: error
  operation-2xx-response: error
  security-defined: error
  boolean-parameter-prefixes: error
  no-unused-components: error
  no-unresolved-refs: error
  no-required-schema-properties-undefined: error
  tag-description: off
  tags-alphabetical: off
  paths-kebab-case: warn
  no-ambiguous-paths: error
  info-license: warn
      
theme:
  openapi:
    theme:
      colors:
        primary:
          main: "#2563EB"
      typography:
        headings:
          fontFamily: 'Roboto, sans-serif' 