type: object
properties:
  id:
    type: string
    description: System-generated unique identifier
    readOnly: true
    example: PlatformConfig:019542f5-b3e7-1d02-0000-000000000003
  umaDomain:
    type: string
    description: UMA domain for this platform
    example: platform.uma.domain
  proxyUmaSubdomain:
    type: string
    description: The subdomain that incoming requests will be proxied to
    example: platform
  webhookEndpoint:
    type: string
    description: URL where webhook notifications will be sent
    example: https://api.mycompany.com/webhooks/uma
  supportedCurrencies:
    type: array
    items:
      $ref: ./PlatformCurrencyConfig.yaml
    description: |
      List of currencies supported by the platform. This is what the platform's
      customers are able to hold, send, and receive.
  isRegulatedFinancialInstitution:
    type: boolean
    description: |
      Whether the platform is a regulated financial institution. This is used to
      determine if the platform's customers must be KYC/KYB'd by Lightspark via
      the KYC link flow. This can only be set by Lightspark during platform
      creation.
    example: false
  createdAt:
    type: string
    format: date-time
    description: Creation timestamp
    readOnly: true
    example: '2025-06-15T12:30:45Z'
  updatedAt:
    type: string
    format: date-time
    description: Last update timestamp
    readOnly: true
    example: '2025-06-15T12:30:45Z'
