get:
  summary: Get platform configuration
  description: Retrieve the current platform configuration
  operationId: getPlatformConfig
  tags:
    - Platform Configuration
  security:
    - BasicAuth: []
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/config/PlatformConfig.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/Error401.yaml
    '500':
      description: Internal service error
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/Error500.yaml
patch:
  summary: Update platform configuration
  description: Update the platform configuration settings
  operationId: updatePlatformConfig
  tags:
    - Platform Configuration
  security:
    - BasicAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            umaDomain:
              type: string
              example: mycompany.com
            webhookEndpoint:
              type: string
              example: https://api.mycompany.com/webhooks/uma
            supportedCurrencies:
              type: array
              items:
                $ref: ../../components/schemas/config/PlatformCurrencyConfig.yaml
        example:
          umaDomain: mycompany.com
          webhookEndpoint: https://api.mycompany.com/webhooks/uma
          supportedCurrencies:
            - currencyCode: USD
              minAmount: 100
              maxAmount: 1000000
              enabledTransactionTypes:
                - OUTGOING
                - INCOMING
              requiredCounterpartyFields:
                - name: FULL_NAME
                  mandatory: true
                - name: NATIONALITY
                  mandatory: true
                - name: BIRTH_DATE
                  mandatory: true
  responses:
    '200':
      description: Configuration updated successfully
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/config/PlatformConfig.yaml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/Error400.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/Error401.yaml
    '500':
      description: Internal service error
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/Error500.yaml
    '501':
      description: Not implemented
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/Error501.yaml
