name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'openapi.yaml'
      - 'docusaurus-docs/**/*.md'
      - '.markdownlint.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'openapi.yaml'
      - 'docusaurus-docs/**/*.md'
      - '.markdownlint.json'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code & Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Check combined schema
        run: |
          npm run build:openapi
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Build produced uncommitted changes in openapi.yaml. Please rerun npm run build:openapi and commit the changes to the combined schema"
            exit 1
          fi
      
      - name: Lint
        run: npm run lint:openapi 